# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default
keybinding:
  universal:
    scrollUpMain-alt1: <c-k>
    scrollDownMain-alt1: <c-j>
    copyToClipboard: y

  commits:
    moveDownCommit: J # move commit down one
    moveUpCommit: K # move commit up one
    renameCommit: R
    renameCommitWithEditor: r
  files:
    commitChanges: C
    commitChangesWithEditor: c
    openStatusFilter: F
    findBaseCommitForFixup: B

os:
  editPreset: "nvim"

git:
  overrideGpg: true

promptToReturnFromSubprocess: false

notARepository: "prompt" # prompt | create | skip

quitOnTopLevelReturn: true
