# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default
keybinding:
  universal:
    scrollUpMain-alt1: <c-b>
    scrollDownMain-alt1: <c-f>
    copyToClipboard: y

  commits:
    moveDownCommit: J # move commit down one
    moveUpCommit: K # move commit up one
    renameCommit: R
    renameCommitWithEditor: r
  files:
    commitChanges: C
    commitChangesWithEditor: c
    openStatusFilter: F
    findBaseCommitForFixup: B

os:
  editPreset: "nvim"

git:
  overrideGpg: true

gui:
  # If true, capture mouse events.
  # When mouse events are captured, it's a little harder to select text: e.g.
  # requiring you to hold the option key when on macOS.
  mouseEvents: true

promptToReturnFromSubprocess: false

notARepository: "skip" # prompt | create | skip
