[[plugin.deps]]
use = "boydaihungst/save-clipboard-to-file"
rev = "9fcd6c4"
hash = "d67c9d3df0b067be229fb526c77b08ae"

[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "4e55902"
hash = "36a484acf6a0a0219c543ccb4cee218f"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "4e55902"
hash = "8da0b15a97b5dfd13941d1ecc617ac7c"

[[plugin.deps]]
use = "stelcodes/bunny"
rev = "7137a44"
hash = "58bfa473bcac8574400e573787954512"

[[plugin.deps]]
use = "dedukun/relative-motions"
rev = "a603d9e"
hash = "e02a788e5b8ae0fb47fd0193dda589cc"

[[plugin.deps]]
use = "ktunprasert/git-files"
rev = "c7289ad"
hash = "cdb1a69bed63211c75b72521bbab875d"

[[plugin.deps]]
use = "dedukun/bookmarks"
rev = "9ef1254"
hash = "92fbb5483657fa7976cdf4e0104e18e0"

[flavor]
deps = []
