# [flavor]
# dark = "kanagawa"

[mgr]
marker_selected = { fg = "yellow", bg = 'yellow' }
marker_copied = { fg = "green", bg = 'green' }
marker_cut = { fg = "magenta", bg = 'magenta' }

[status]
overall = { fg = "gray" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }


[which]
mask = { bg = "reset" }
