# [flavor]
# dark = "kanagawa"

[indicator]
padding = { open = "█", close = "█" }

[status]
overall = { fg = "gray" }

[mgr]
marker_selected = { fg = "yellow", bg = 'yellow' }
marker_copied = { fg = "green", bg = 'green' }
marker_cut = { fg = "magenta", bg = 'magenta' }
